# Generated by Django 3.2.3 on 2021-05-21 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_author_follow_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
